<?php

/**
 * @file
 * Contains hooks for date_recur module.
 */

use Drupal\date_recur\DateRecurCachedHooks;

/**
 * Implements hook_theme().
 */
function date_recur_theme($existing, $type, $theme, $path) {
  /** @var \Drupal\date_recur\DateRecurCachedHooks $cachedHooks */
  $cachedHooks = \Drupal::classResolver(DateRecurCachedHooks::class);
  return $cachedHooks->hookTheme($existing, $type, $theme, $path);
}

/**
 * Implements hook_field_info_alter().
 */
function date_recur_field_info_alter(&$info) {
  /** @var \Drupal\date_recur\DateRecurCachedHooks $cachedHooks */
  $cachedHooks = \Drupal::classResolver(DateRecurCachedHooks::class);
  $cachedHooks->fieldInfoAlter($info);
}
